CREATE TABLE sale (
    id_sale INT(11) NOT NULL AUTO_INCREMENT,
    id_client INT(11),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_sale),
    CONSTRAINT fk_sale_client FOREIGN KEY (id_client) REFERENCES client(id_client)
);

-- created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
-- updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP